// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using webAPI.Data;

namespace webAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211212032801_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("webAPI.Models.Furniture", b =>
                {
                    b.Property<int>("FurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("FurMaterial")
                        .HasColumnType("text");

                    b.Property<string>("FurName")
                        .HasColumnType("text");

                    b.Property<int>("FurPrice")
                        .HasColumnType("integer");

                    b.Property<string>("FurType")
                        .HasColumnType("text");

                    b.HasKey("FurId");

                    b.ToTable("furnitures");
                });
#pragma warning restore 612, 618
        }
    }
}
