// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using webAPI.Data;

namespace webAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("webAPI.Models.Furniture", b =>
                {
                    b.Property<int>("FurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("FurMaterial")
                        .HasColumnType("text");

                    b.Property<string>("FurName")
                        .HasColumnType("text");

                    b.Property<int>("FurPrice")
                        .HasColumnType("integer");

                    b.Property<string>("FurType")
                        .HasColumnType("text");

                    b.Property<int?>("GiftID")
                        .HasColumnType("integer");

                    b.HasKey("FurId");

                    b.HasIndex("GiftID");

                    b.ToTable("furnitures");
                });

            modelBuilder.Entity("webAPI.Models.Gift", b =>
                {
                    b.Property<int>("GiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("GiftName")
                        .HasColumnType("text");

                    b.Property<string>("GiftType")
                        .HasColumnType("text");

                    b.HasKey("GiftID");

                    b.ToTable("gift");
                });

            modelBuilder.Entity("webAPI.Models.Furniture", b =>
                {
                    b.HasOne("webAPI.Models.Gift", "gift")
                        .WithMany()
                        .HasForeignKey("GiftID");

                    b.Navigation("gift");
                });
#pragma warning restore 612, 618
        }
    }
}
